import type {IconNode} from 'lucide';
import {
    Anchor,
    Archive,
    Award,
    Bell,
    Bookmark,
    Box,
    Calendar,
    Clock,
    Cog,
    Compass,
    Crown,
    Flag,
    Folder,
    Hash,
    House,
    Inbox,
    Info,
    Layers,
    LifeBuoy,
    Link,
    List,
    Lock,
    Mail,
    Map as MapIcon,
    Megaphone,
    Package,
    Paperclip,
    Pin,
    Search,
    Settings,
    Shield,
    Star,
    Tag,
    Target,
    Trophy,
    Users,
    Wallet,
    Wrench,
    AtSign,
    Handshake,
    HeartHandshake,
    MessageCircle,
    MessageSquare,
    MessagesSquare,
    Mic,
    Phone,
    RadioTower,
    Quote,
    Radio,
    Reply,
    Send,
    Speech,
    Video,
    Voicemail,
    Volume2,
    Vote,
    Bomb,
    Castle,
    Crosshair,
    Dice5,
    Drama,
    Ghost,
    Gamepad2,
    Joystick,
    Puzzle,
    Rocket,
    Scroll,
    Shapes,
    Skull,
    Sparkles,
    Swords,
    Tent,
    WandSparkles,
    Zap,
    Aperture,
    Book,
    BookOpen,
    Camera,
    Clapperboard,
    Disc3,
    Film,
    Headphones,
    Image as ImageIcon,
    Images,
    Library,
    Music,
    Newspaper,
    Palette,
    Piano,
    Projector,
    Tv,
    SquarePlay,
    Anvil,
    Building2,
    Church,
    Factory,
    Fence,
    Landmark,
    MapPin,
    Mountain,
    Route,
    School,
    Ship,
    Signpost,
    Store,
    TrainFront,
    Warehouse,
    Waypoints,
    Backpack,
    Banknote,
    Beaker,
    Bike,
    Briefcase,
    Brush,
    Car,
    ChefHat,
    Coffee,
    Coins,
    Cpu,
    Croissant,
    Gem,
    Gift,
    Glasses,
    Hammer,
    Key,
    Lamp,
    Laptop,
    Pizza,
    Scissors,
    Shirt,
    ShoppingCart,
    Sofa,
    Syringe,
    Utensils,
    Wine,
    Bird,
    Bug,
    Cat,
    Cherry,
    Cloud,
    Clover,
    Dog,
    Droplet,
    Feather,
    Fish,
    Flame,
    Flower2,
    Leaf,
    Moon,
    Rabbit,
    Snowflake,
    Sprout,
    Sun,
    TreePine,
    WavesHorizontal,
    Activity,
    Asterisk,
    Atom,
    Binary,
    BrainCircuit,
    CircleDot,
    Code,
    Diamond,
    Divide,
    Eye,
    Heart,
    Hexagon,
    Infinity as InfinityIcon,
    Orbit,
    Percent,
    Pyramid,
    Sigma,
    Spade,
    Triangle,
} from 'lucide';

export type ChannelIconGroup =
    'general' | 'communication' | 'gaming' | 'media' | 'places' | 'objects' | 'nature' | 'symbols';

export interface ChannelIconEntry {
    /** The stored value. Must satisfy the server's `^[a-z0-9-]{1,48}$`. */
    name: string;
    icon: IconNode;
    group: ChannelIconGroup;
}

/** Picker order. */
export const CHANNEL_ICON_GROUPS: readonly ChannelIconGroup[] = [
    'general',
    'communication',
    'gaming',
    'media',
    'places',
    'objects',
    'nature',
    'symbols',
];

/** The only place a channel icon may come from. The picker and the name lookup both derive from it, so a listed icon is always resolvable and a resolvable icon is always listed. */
export const CHANNEL_ICON_CATALOG: readonly ChannelIconEntry[] = [
    {name: 'anchor', icon: Anchor, group: 'general'},
    {name: 'archive', icon: Archive, group: 'general'},
    {name: 'award', icon: Award, group: 'general'},
    {name: 'bell', icon: Bell, group: 'general'},
    {name: 'bookmark', icon: Bookmark, group: 'general'},
    {name: 'box', icon: Box, group: 'general'},
    {name: 'calendar', icon: Calendar, group: 'general'},
    {name: 'clock', icon: Clock, group: 'general'},
    {name: 'cog', icon: Cog, group: 'general'},
    {name: 'compass', icon: Compass, group: 'general'},
    {name: 'crown', icon: Crown, group: 'general'},
    {name: 'flag', icon: Flag, group: 'general'},
    {name: 'folder', icon: Folder, group: 'general'},
    {name: 'hash', icon: Hash, group: 'general'},
    {name: 'house', icon: House, group: 'general'},
    {name: 'inbox', icon: Inbox, group: 'general'},
    {name: 'info', icon: Info, group: 'general'},
    {name: 'layers', icon: Layers, group: 'general'},
    {name: 'life-buoy', icon: LifeBuoy, group: 'general'},
    {name: 'link', icon: Link, group: 'general'},
    {name: 'list', icon: List, group: 'general'},
    {name: 'lock', icon: Lock, group: 'general'},
    {name: 'mail', icon: Mail, group: 'general'},
    {name: 'map', icon: MapIcon, group: 'general'},
    {name: 'megaphone', icon: Megaphone, group: 'general'},
    {name: 'package', icon: Package, group: 'general'},
    {name: 'paperclip', icon: Paperclip, group: 'general'},
    {name: 'pin', icon: Pin, group: 'general'},
    {name: 'search', icon: Search, group: 'general'},
    {name: 'settings', icon: Settings, group: 'general'},
    {name: 'shield', icon: Shield, group: 'general'},
    {name: 'star', icon: Star, group: 'general'},
    {name: 'tag', icon: Tag, group: 'general'},
    {name: 'target', icon: Target, group: 'general'},
    {name: 'trophy', icon: Trophy, group: 'general'},
    {name: 'users', icon: Users, group: 'general'},
    {name: 'wallet', icon: Wallet, group: 'general'},
    {name: 'wrench', icon: Wrench, group: 'general'},

    {name: 'at-sign', icon: AtSign, group: 'communication'},
    {name: 'handshake', icon: Handshake, group: 'communication'},
    {name: 'heart-handshake', icon: HeartHandshake, group: 'communication'},
    {name: 'message-circle', icon: MessageCircle, group: 'communication'},
    {name: 'message-square', icon: MessageSquare, group: 'communication'},
    {name: 'messages-square', icon: MessagesSquare, group: 'communication'},
    {name: 'mic', icon: Mic, group: 'communication'},
    {name: 'phone', icon: Phone, group: 'communication'},
    {name: 'radio-tower', icon: RadioTower, group: 'communication'},
    {name: 'quote', icon: Quote, group: 'communication'},
    {name: 'radio', icon: Radio, group: 'communication'},
    {name: 'reply', icon: Reply, group: 'communication'},
    {name: 'send', icon: Send, group: 'communication'},
    {name: 'speech', icon: Speech, group: 'communication'},
    {name: 'video', icon: Video, group: 'communication'},
    {name: 'voicemail', icon: Voicemail, group: 'communication'},
    {name: 'volume-2', icon: Volume2, group: 'communication'},
    {name: 'vote', icon: Vote, group: 'communication'},

    {name: 'bomb', icon: Bomb, group: 'gaming'},
    {name: 'castle', icon: Castle, group: 'gaming'},
    {name: 'crosshair', icon: Crosshair, group: 'gaming'},
    {name: 'dice-5', icon: Dice5, group: 'gaming'},
    {name: 'drama', icon: Drama, group: 'gaming'},
    {name: 'gamepad-2', icon: Gamepad2, group: 'gaming'},
    {name: 'ghost', icon: Ghost, group: 'gaming'},
    {name: 'joystick', icon: Joystick, group: 'gaming'},
    {name: 'puzzle', icon: Puzzle, group: 'gaming'},
    {name: 'rocket', icon: Rocket, group: 'gaming'},
    {name: 'scroll', icon: Scroll, group: 'gaming'},
    {name: 'shapes', icon: Shapes, group: 'gaming'},
    {name: 'skull', icon: Skull, group: 'gaming'},
    {name: 'sparkles', icon: Sparkles, group: 'gaming'},
    {name: 'swords', icon: Swords, group: 'gaming'},
    {name: 'tent', icon: Tent, group: 'gaming'},
    {name: 'wand-sparkles', icon: WandSparkles, group: 'gaming'},
    {name: 'zap', icon: Zap, group: 'gaming'},

    {name: 'aperture', icon: Aperture, group: 'media'},
    {name: 'book', icon: Book, group: 'media'},
    {name: 'book-open', icon: BookOpen, group: 'media'},
    {name: 'camera', icon: Camera, group: 'media'},
    {name: 'clapperboard', icon: Clapperboard, group: 'media'},
    {name: 'disc-3', icon: Disc3, group: 'media'},
    {name: 'film', icon: Film, group: 'media'},
    {name: 'headphones', icon: Headphones, group: 'media'},
    {name: 'image', icon: ImageIcon, group: 'media'},
    {name: 'images', icon: Images, group: 'media'},
    {name: 'library', icon: Library, group: 'media'},
    {name: 'music', icon: Music, group: 'media'},
    {name: 'newspaper', icon: Newspaper, group: 'media'},
    {name: 'palette', icon: Palette, group: 'media'},
    {name: 'piano', icon: Piano, group: 'media'},
    {name: 'projector', icon: Projector, group: 'media'},
    {name: 'tv', icon: Tv, group: 'media'},
    {name: 'square-play', icon: SquarePlay, group: 'media'},

    {name: 'anvil', icon: Anvil, group: 'places'},
    {name: 'building-2', icon: Building2, group: 'places'},
    {name: 'church', icon: Church, group: 'places'},
    {name: 'factory', icon: Factory, group: 'places'},
    {name: 'fence', icon: Fence, group: 'places'},
    {name: 'landmark', icon: Landmark, group: 'places'},
    {name: 'map-pin', icon: MapPin, group: 'places'},
    {name: 'mountain', icon: Mountain, group: 'places'},
    {name: 'route', icon: Route, group: 'places'},
    {name: 'school', icon: School, group: 'places'},
    {name: 'ship', icon: Ship, group: 'places'},
    {name: 'signpost', icon: Signpost, group: 'places'},
    {name: 'store', icon: Store, group: 'places'},
    {name: 'train-front', icon: TrainFront, group: 'places'},
    {name: 'warehouse', icon: Warehouse, group: 'places'},
    {name: 'waypoints', icon: Waypoints, group: 'places'},

    {name: 'backpack', icon: Backpack, group: 'objects'},
    {name: 'banknote', icon: Banknote, group: 'objects'},
    {name: 'beaker', icon: Beaker, group: 'objects'},
    {name: 'bike', icon: Bike, group: 'objects'},
    {name: 'briefcase', icon: Briefcase, group: 'objects'},
    {name: 'brush', icon: Brush, group: 'objects'},
    {name: 'car', icon: Car, group: 'objects'},
    {name: 'chef-hat', icon: ChefHat, group: 'objects'},
    {name: 'coffee', icon: Coffee, group: 'objects'},
    {name: 'coins', icon: Coins, group: 'objects'},
    {name: 'cpu', icon: Cpu, group: 'objects'},
    {name: 'croissant', icon: Croissant, group: 'objects'},
    {name: 'gem', icon: Gem, group: 'objects'},
    {name: 'gift', icon: Gift, group: 'objects'},
    {name: 'glasses', icon: Glasses, group: 'objects'},
    {name: 'hammer', icon: Hammer, group: 'objects'},
    {name: 'key', icon: Key, group: 'objects'},
    {name: 'lamp', icon: Lamp, group: 'objects'},
    {name: 'laptop', icon: Laptop, group: 'objects'},
    {name: 'pizza', icon: Pizza, group: 'objects'},
    {name: 'scissors', icon: Scissors, group: 'objects'},
    {name: 'shirt', icon: Shirt, group: 'objects'},
    {name: 'shopping-cart', icon: ShoppingCart, group: 'objects'},
    {name: 'sofa', icon: Sofa, group: 'objects'},
    {name: 'syringe', icon: Syringe, group: 'objects'},
    {name: 'utensils', icon: Utensils, group: 'objects'},
    {name: 'wine', icon: Wine, group: 'objects'},

    {name: 'bird', icon: Bird, group: 'nature'},
    {name: 'bug', icon: Bug, group: 'nature'},
    {name: 'cat', icon: Cat, group: 'nature'},
    {name: 'cherry', icon: Cherry, group: 'nature'},
    {name: 'cloud', icon: Cloud, group: 'nature'},
    {name: 'clover', icon: Clover, group: 'nature'},
    {name: 'dog', icon: Dog, group: 'nature'},
    {name: 'droplet', icon: Droplet, group: 'nature'},
    {name: 'feather', icon: Feather, group: 'nature'},
    {name: 'fish', icon: Fish, group: 'nature'},
    {name: 'flame', icon: Flame, group: 'nature'},
    {name: 'flower-2', icon: Flower2, group: 'nature'},
    {name: 'leaf', icon: Leaf, group: 'nature'},
    {name: 'moon', icon: Moon, group: 'nature'},
    {name: 'rabbit', icon: Rabbit, group: 'nature'},
    {name: 'snowflake', icon: Snowflake, group: 'nature'},
    {name: 'sprout', icon: Sprout, group: 'nature'},
    {name: 'sun', icon: Sun, group: 'nature'},
    {name: 'tree-pine', icon: TreePine, group: 'nature'},
    {name: 'waves-horizontal', icon: WavesHorizontal, group: 'nature'},

    {name: 'activity', icon: Activity, group: 'symbols'},
    {name: 'asterisk', icon: Asterisk, group: 'symbols'},
    {name: 'atom', icon: Atom, group: 'symbols'},
    {name: 'binary', icon: Binary, group: 'symbols'},
    {name: 'brain-circuit', icon: BrainCircuit, group: 'symbols'},
    {name: 'circle-dot', icon: CircleDot, group: 'symbols'},
    {name: 'code', icon: Code, group: 'symbols'},
    {name: 'diamond', icon: Diamond, group: 'symbols'},
    {name: 'divide', icon: Divide, group: 'symbols'},
    {name: 'eye', icon: Eye, group: 'symbols'},
    {name: 'heart', icon: Heart, group: 'symbols'},
    {name: 'hexagon', icon: Hexagon, group: 'symbols'},
    {name: 'infinity', icon: InfinityIcon, group: 'symbols'},
    {name: 'orbit', icon: Orbit, group: 'symbols'},
    {name: 'percent', icon: Percent, group: 'symbols'},
    {name: 'pyramid', icon: Pyramid, group: 'symbols'},
    {name: 'sigma', icon: Sigma, group: 'symbols'},
    {name: 'spade', icon: Spade, group: 'symbols'},
    {name: 'triangle', icon: Triangle, group: 'symbols'},
];

const ICON_BY_NAME = new Map<string, IconNode>(CHANNEL_ICON_CATALOG.map(e => [e.name, e.icon]));

/** Null for anything this build does not ship, which is what keeps an icon name from a newer server off the render path. */
export function lookupChannelIcon(name: string | null | undefined): IconNode | null {
    if (!name) return null;
    return ICON_BY_NAME.get(name) ?? null;
}
