import {MessageEncryptionState} from "../../enums/message-encryption-state.enum";
import {MessageType} from '../../enums/message-type.enum';

/**
 * <p>Deliberately has no `url`: the payload carries `thumbnailUrl` and nothing else, so code
 * reaching for "the attachment's URL" was getting `undefined` where the type promised a string -
 * or, worse, falling back to the thumbnail and downloading a downscaled preview. Build the
 * full-size address from the id with `FileService.attachmentDownloadUrl`.</p>
 */
export interface MessageAttachment {
    id: string;
    fileName: string;
    contentType: string;
    thumbnailUrl?: string;
}

export interface MessageReaction {
    contextId: string;
    messageId: string;
    emoji: string;
    emojiId?: string | null;
    userId: string;
    createdAt: string;
    conversationId: string | null;
    channelId: string | null;
}

export interface MessageEmbedField {
    name: string;
    value: string;
    inline: boolean;
}

export interface MessageEmbedAuthor {
    name: string;
    url?: string;
    iconUrl?: string;
    proxyIconUrl?: string;
}

export interface MessageEmbedFooter {
    text: string;
    iconUrl?: string;
    proxyIconUrl?: string;
}

export interface MessageEmbedProvider {
    name: string;
    url?: string;
}

/**
 * Picks the card layout. Absent on older bot embeds, which are all `rich`.
 */
export type MessageEmbedType = 'rich' | 'link' | 'article' | 'image' | 'video' | 'gifv';

/**
 * An image, thumbnail or player frame on an embed.
 *
 * <p><b>Render `proxyUrl`, never `url`.</b> `url` is the third-party origin's own address, so
 * loading it hands that origin the IP address, rough location and read time of everyone who
 * scrolls past a link one other person posted. `proxyUrl` is our re-hosted copy: unauthenticated
 * (an `<img>` carries no token), immutable, and cached for a week - so no cache-busting and no
 * `Authorization` header. Keep `url` for an "open original" affordance only.</p>
 */
export interface MessageEmbedMedia {
    /** The origin's own URL. Do not put this in a `src`. */
    url: string;
    /** Our re-hosted copy - a fully-qualified absolute URL. Absent if the media was not fetched. */
    proxyUrl?: string;
    /** True measured pixel dimensions. Used to reserve layout space before the image loads. */
    width?: number;
    height?: number;
    contentType?: string;
    /** BlurHash string - decoded into a blurred placeholder while the real image loads. */
    placeholder?: string;
    /** Which encoding `placeholder` uses. 1 = BlurHash; anything else must be ignored. */
    placeholderVersion?: number;
}

/**
 * A card under a message: either written by a bot (`rich`) or generated by the server from a link.
 *
 * <p>Everything here comes from a third-party page and is attacker-controlled text. It arrives
 * HTML-decoded and stripped of control characters, but it is still text a stranger wrote - render
 * it as text, never as HTML and never through a markdown pass that could resolve to an image.</p>
 */
export interface MessageEmbed {
    type?: MessageEmbedType;
    title?: string;
    description?: string;
    url?: string;
    /** ISO-8601. The *content's* date (e.g. publication), not when it was unfurled. */
    timestamp?: string;
    color?: string | null;
    provider?: MessageEmbedProvider;
    author?: MessageEmbedAuthor;
    /** Small, beside the text - also the poster frame for a video. */
    thumbnail?: MessageEmbedMedia;
    /** Large, full-width below the text. */
    image?: MessageEmbedMedia;
    /** The in-app player. Only ever a server-whitelisted provider; still sandboxed on render. */
    video?: MessageEmbedMedia;
    /** Bots only, at most 25. Generated previews never populate this. */
    fields?: MessageEmbedField[];
    footer?: MessageEmbedFooter;
    /** Bitfield - see {@link EmbedFlags}. */
    flags?: number;
}

export const EmbedFlags = {
    /** Bit 16: generated by the server from a link, rather than written by the message's author. */
    Generated: 1 << 16,
} as const;

/** Discord-compatible message bitfield. */
export const MessageFlags = {
    /** Bit 2: a person removed this message's previews, for everyone who can see it. */
    SuppressEmbeds: 1 << 2,
} as const;

export interface MessageDto {
    id: string;
    createdAt: Date;
    updatedAt: Date;
    content: string;
    channelId: string | undefined;
    conversationId: string | undefined;
    authorId: string;
    isPending: boolean;
    isFailed: boolean;
    attachments: MessageAttachment[];
    inReplyTo: string | undefined;
    mentions: string[];
    roleMentions?: string[];
    mentionsEveryone?: boolean;
    mentionsHere?: boolean;
    encryptionState: MessageEncryptionState;
    mlsEpoch: number | undefined;
    mlsSequenceNumber: number | undefined;
    /** Which encryption era of the context this ciphertext belongs to. Null on plaintext. */
    mlsGeneration?: number | null;
    /** Client-only: ciphertext this device can no longer read - MLS ratchets forward only. */
    undecryptable?: boolean;
    senderDeviceId: string | undefined;
    type: MessageType;
    reactions?: MessageReaction[];
    /** Client-only: marks this entity as a synthetic placeholder for an in-flight/failed bot command invocation, not a real persisted message. */
    isBotCommandPlaceholder?: boolean;
    /**
     * Client-only: a bot reply only this user was sent, which the server never stored
     * (`guild.EphemeralMessageCreated`).
     *
     * <p>It lives in the store so the channel can render it, and nowhere else - a reload loses it,
     * which is the whole point. Nothing may offer edit, delete, pin or reply on it: there is no
     * server-side row for any of those to act on, and every one of them would 404.</p>
     */
    isEphemeral?: boolean;
    embedsJson?: string;
    /**
     * When the **author** last changed the text, or null if they never did.
     *
     * <p>This is what drives the "(edited)" marker - never `updatedAt`. `updatedAt` is bumped by
     * anything that writes the row, including a preview attaching a second after the message was
     * posted, so driving the marker off it labels every message containing a link as edited by
     * nobody.</p>
     */
    editedAt?: string | null;
    /** Message bitfield - see {@link MessageFlags}. */
    flags?: number;
    systemMessageVariant?: number;
    isPinned?: boolean;
    pinnedAt?: string;
    pinnedById?: string;
}

export interface EmbedSuppressionResponse {
    messageId: string;
    suppressed: boolean;
}

export interface PinMessageResponse {
    success: boolean;
    channelId?: string;
    conversationId?: string;
    authorId?: string;
    pinnedById?: string;
    pinnedAt?: string;
}
