import {MessageEncryptionState} from '../../enums/message-encryption-state.enum';
import {MessageType} from '../../enums/message-type.enum';
import {PersonaMentionDto} from '../../features/guild/personas/persona-mention';

/** Has no `url`. Build the full-size address from the id with `FileService.attachmentDownloadUrl`. */
export interface MessageAttachment {
    id: string;
    fileName: string;
    contentType: string;
    thumbnailUrl?: string;
}

export interface MessageReaction {
    contextId: string;
    messageId: string;
    emoji: string;
    emojiId?: string | null;
    userId: string;
    createdAt: string;
    conversationId: string | null;
    channelId: string | null;
}

export interface MessageEmbedField {
    name: string;
    value: string;
    inline: boolean;
}

/** Multi-word fields inside an embed are snake_case; the message fields around them are camelCase. */
export interface MessageEmbedAuthor {
    name: string;
    url?: string;
    icon_url?: string;
    proxy_icon_url?: string;
}

export interface MessageEmbedFooter {
    text: string;
    icon_url?: string;
    proxy_icon_url?: string;
}

export interface MessageEmbedProvider {
    name: string;
    url?: string;
}

/**
 * Picks the card layout. Absent on older bot embeds, which are all `rich`. An unrecognised
 * `venta.*` type must be ignored outright, never fall back to the link layout.
 */
export type MessageEmbedType =
    | 'rich'
    | 'link'
    | 'article'
    | 'image'
    | 'video'
    | 'gifv'
    | 'venta.invite'
    | 'venta.wiki_page'
    | 'venta.voice_invite';

/**
 * The identity of whatever an instance-local link points at. Identifiers only, never a URL to call.
 * Trust it only when the embed carries {@link EmbedFlags.Generated}.
 */
export interface MessageEmbedVenta {
    /** `type` without the `venta.` prefix, so one value can be switched on. */
    kind: 'invite' | 'wiki_page' | 'voice_invite' | (string & {});
    /** Whether the server filled in title/description, or deliberately left them out. */
    resolved: boolean;
    guild_id?: string;

    /** Invite only. Always the canonical code, even when the pasted link was a vanity URL. */
    invite_code?: string;
    /** Invite: the channel a joiner lands on. Voice invite: the channel being asked into. An id, never a name. */
    channel_id?: string;
    /** ISO-8601. On an invite, absent means it never expires. Always present on a voice invite. */
    expires_at?: string;
    /** Invite only. Absent for unlimited. */
    max_uses?: number;

    /** Wiki only. */
    page_id?: string;

    /** Voice invite only: the ring this card was written for. Live only until {@link expires_at}. */
    ring_id?: string;
    /** Voice invite only: who did the asking. */
    inviter_id?: string;
    /** Voice invite only: the channel's name when the invitation was sent. Render it; do not refetch. */
    channel_name?: string;
}

/** An image, thumbnail or player frame on an embed. Render `proxy_url`, never `url`. */
export interface MessageEmbedMedia {
    /** The origin's own URL. Do not put this in a `src`. */
    url: string;
    /** Our re-hosted copy, a fully-qualified absolute URL. Absent if the media was not fetched. */
    proxy_url?: string;
    /** True measured pixel dimensions. Used to reserve layout space before the image loads. */
    width?: number;
    height?: number;
    content_type?: string;
    /** BlurHash string, decoded into a blurred placeholder while the real image loads. */
    placeholder?: string;
    /** Which encoding `placeholder` uses. 1 = BlurHash; anything else must be ignored. */
    placeholder_version?: number;
}

/**
 * A card under a message: written by a bot (`rich`) or generated by the server from a link.
 * Every string here is attacker-controlled; render as text, never as HTML or markdown.
 */
export interface MessageEmbed {
    type?: MessageEmbedType;
    title?: string;
    description?: string;
    url?: string;
    /** ISO-8601. The content's own date (e.g. publication), not when it was unfurled. */
    timestamp?: string;
    color?: string | null;
    provider?: MessageEmbedProvider;
    author?: MessageEmbedAuthor;
    /** Small, beside the text. Also the poster frame for a video. */
    thumbnail?: MessageEmbedMedia;
    /** Large, full-width below the text. */
    image?: MessageEmbedMedia;
    /** The in-app player. Only ever a server-whitelisted provider; still sandboxed on render. */
    video?: MessageEmbedMedia;
    /** Bots only, at most 25. Generated previews never populate this. */
    fields?: MessageEmbedField[];
    footer?: MessageEmbedFooter;
    /** Bitfield; see {@link EmbedFlags}. */
    flags?: number;
    /** Present only on `venta.*` embeds. Trust it only when {@link EmbedFlags.Generated} is set. */
    venta?: MessageEmbedVenta;
}

export const EmbedFlags = {
    /** Bit 16: generated by the server from a link, rather than written by the message's author. */
    Generated: 1 << 16,
} as const;

/** Discord-compatible message bitfield. */
export const MessageFlags = {
    /** Bit 2: a person removed this message's previews, for everyone who can see it. */
    SuppressEmbeds: 1 << 2,
    /** Bit 5: derived server-side from threadId, so the two can never disagree. */
    HasThread: 1 << 5,
} as const;

export interface MessageDto {
    id: string;
    createdAt: Date;
    updatedAt: Date;
    content: string;
    channelId: string | undefined;
    conversationId: string | undefined;
    authorId: string;
    /** Denormalised at send time. Set for personas and webhooks; `authorId` stays the real account. */
    authorDisplayName?: string | null;
    authorAvatarUrl?: string | null;
    /** The character this was spoken as. Absent on a webhook, which has the overrides but no persona. */
    personaId?: string | null;
    isPending: boolean;
    isFailed: boolean;
    attachments: MessageAttachment[];
    inReplyTo: string | undefined;
    mentions: string[];
    /**
     * Characters named in the body as `<@pers_...>`. A separate list from {@link mentions} because
     * a character mention notifies its owner without ever naming them to anyone else, and because
     * the display fields are the only way to draw a character the reader cannot speak as.
     */
    personaMentions?: PersonaMentionDto[];
    roleMentions?: string[];
    mentionsEveryone?: boolean;
    mentionsHere?: boolean;
    encryptionState: MessageEncryptionState;
    mlsEpoch: number | undefined;
    mlsSequenceNumber: number | undefined;
    /** Which encryption era of the context this ciphertext belongs to. Null on plaintext. */
    mlsGeneration?: number | null;
    /** Client-only: ciphertext this device can no longer read. MLS ratchets forward only. */
    undecryptable?: boolean;
    senderDeviceId: string | undefined;
    type: MessageType;
    reactions?: MessageReaction[];
    /** Client-only: marks this entity as a synthetic placeholder for an in-flight/failed bot command invocation, not a real persisted message. */
    isBotCommandPlaceholder?: boolean;
    /**
     * Client-only: a bot reply only this user was sent, never stored server-side. Nothing may offer
     * edit, delete, pin or reply on it.
     */
    isEphemeral?: boolean;
    embedsJson?: string;
    /** When the author last changed the text, or null if they never did. Drives "(edited)", never `updatedAt`. */
    editedAt?: string | null;
    /** Message bitfield; see {@link MessageFlags}. */
    flags?: number;
    /** The thread started from this message, or null. */
    threadId?: string | null;
    systemMessageVariant?: number;
    isPinned?: boolean;
    pinnedAt?: string;
    pinnedById?: string;
}

export interface EmbedSuppressionResponse {
    messageId: string;
    suppressed: boolean;
}

export interface PinMessageResponse {
    success: boolean;
    channelId?: string;
    conversationId?: string;
    authorId?: string;
    pinnedById?: string;
    pinnedAt?: string;
}
