import {Component, inject, signal} from '@angular/core';
import {HttpClient} from '@angular/common/http';
import {DomSanitizer, SafeHtml} from '@angular/platform-browser';
import {Button} from 'primeng/button';
import {marked} from 'marked';
import DOMPurify from 'dompurify';
import {UpdateService} from '../../../../../services/update.service';
import {AppInfoService} from '../../../../../services/app-info.service';

/**
 * Served from the frontend bundle rather than as a Tauri resource, so it also exists under
 * `ng serve`. Generated by `scripts/generate-notices.js` - see `bun run licenses`.
 */
const NOTICES_URL = 'assets/THIRD-PARTY-NOTICES.md';

const NOTICES_PURIFY_CONFIG = {
    ALLOWED_TAGS: [
        'h1', 'h2', 'h3', 'h4', 'h5', 'h6',
        'p', 'br', 'hr',
        'strong', 'em', 'code', 'pre',
        'ul', 'ol', 'li',
        'blockquote',
        'a', 'span', 'div',
    ],
    ALLOWED_ATTR: ['href', 'id', 'class', 'target', 'rel'],
};

type NoticesState = 'idle' | 'loading' | 'ready' | 'error';

@Component({
    selector: 'app-about-settings',
    imports: [Button],
    templateUrl: './about-settings.component.html',
    styleUrl: './about-settings.component.css',
})
export class AboutSettingsComponent {
    protected readonly updateService = inject(UpdateService);
    protected readonly appInfo = inject(AppInfoService);
    private readonly http = inject(HttpClient);
    private readonly sanitizer = inject(DomSanitizer);

    protected readonly noticesState = signal<NoticesState>('idle');
    protected readonly notices = signal<SafeHtml>('');

    /**
     * Fetched and rendered on demand. The notices run to roughly 600 kB covering some 1,100
     * packages, and parsing that into DOM is not work worth doing for everyone who opens settings
     * to change their microphone.
     */
    protected loadNotices(): void {
        if (this.noticesState() === 'loading' || this.noticesState() === 'ready') return;
        this.noticesState.set('loading');

        this.http.get(NOTICES_URL, {responseType: 'text'}).subscribe({
            next: markdown => {
                const html = DOMPurify.sanitize(marked.parse(markdown) as string, NOTICES_PURIFY_CONFIG);
                this.notices.set(this.sanitizer.bypassSecurityTrustHtml(String(html)));
                this.noticesState.set('ready');
            },
            error: () => this.noticesState.set('error'),
        });
    }
}
